<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <SelfContained>true</SelfContained>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SudokuLib/SudokuLib.csproj" />
    <ProjectReference Include="../SudokuGraphics/SudokuGraphics.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="../release-puzzles/tier*.puzzles" Link="%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
